### ISSUE TITLE
Issues modding Derail Valley on Linux Mint 20.3 Cinnamon

### ISSUE THREAD

**Issue by Doaner** [newman55/unity-mod-manager#92]
Hello! I'm having an issue getting mods to load on Linux. I am running the UMM through Mono and I made a symbolic link as well. UMM detects the game version and I can install mods, however, the game does not load the mods or UMM when I launch it. I have been successful in Windows 10 and 11 by using DoorstopProxy, but Assembly does not work on WIndows. I think that may be the issue here, as Assembly is my only option. I also copied over my game files from Windows and i still does not work. Thank you!

**Comment by newman55** [comment]
Try asking on nexus if it works for others. I've never had this game, so I can't help much here. Sorry.

**Comment by Doaner** [comment]
Thanks for the reply! Let me try that.

**Comment by GamingCoookie** [comment]
Assembly does not work for Derail Valley. You need DoorstopProxy

**Comment by Sweeper5** [comment]
I can add that this is a generic Linux issue due to the fact that the Doorstop loading isn't there for Derail Valley.
If you try to use Assembly, you can run the game, no mods load, and the mod menu in the game is missing data, like if you were missing fonts.
Game will still run fine however, if you try to do a Doorstop load via Wine, it will fail with the following log:
`[6:46 PM] Game changed to 'Derail Valley'.
[6:46 PM] Game path 'C:\Derail.Valley'.
[6:46 PM] Checking for updates.
[6:46 PM] No updates.
[6:46 PM] =======================================
[6:46 PM] Deleting files from game...
[6:46 PM]   'winhttp.dll'
[6:46 PM]   'doorstop_config.ini'
[6:46 PM] Copying files to game...
[6:46 PM]   'winhttp_x64.dll'
[6:46 PM] System.IO.FileNotFoundException: Could not find file 'Z:\home\sweeper\Games\derail_valley\winhttp_x64.dll'.
File name: 'Z:\home\sweeper\Games\derail_valley\winhttp_x64.dll'
  at System.IO.FileSystem.CopyFile (System.String sourceFullPath, System.String destFullPath, System.Boolean overwrite) [0x00060] in <e70d6e9587d64cb3abb4b3f99bbf5a0d>:0 
  at System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) [0x00062] in <e70d6e9587d64cb3abb4b3f99bbf5a0d>:0 
  at UnityModManagerNet.Installer.UnityModManagerForm.InstallDoorstop (UnityModManagerNet.Installer.UnityModManagerForm+Actions action, System.Boolean write) [0x000e9] in <2e855c41b3ec46d28b4a87ee1fde0a94>:0 
[6:46 PM] Installation failed.`

**Comment by newman55** [comment]
Don't copy UMM into the game

**Comment by Sweeper5** [comment]
I am not copying UMM into the game folder.
UMM rests one level above or below, Derail Valley is housed at C:\Derail Valley
While UMM according to Wine sits in C:\unity.
The reason you are confused is because I named the Wine prefix, or Windows "installation" in other words, "derail_valley"

**Comment by newman55** [comment]
Your UMM uses paths to copy as Z:\home\sweeper\Games\derail_valley\, but should use itself. I do not know how to reproduce it.

**Comment by newman55** [comment]
I think I found a mistake, wait for the fix

**Comment by newman55** [comment]
Fixed

**Comment by Sweeper5** [comment]
Just did a few test runs, and it still doesn't work.
I will give newman55 here probs for solving and getting rid of the errors in the log, however I fear that the version of DoorstopUnity is the culprit as it dumps no errors, but doesn't seem to do much in the game.

While there is a Linux version of DoorstopUnity, I do not know how well that would couple up to a game under Wine.
Still, thank you for at least making some progress, but it seems Derail Valley will have to be vanilla for a while longer.

**Comment by ToastedWookiee** [comment]
Using Wine to install the Doorstop version works, then in steam you need to add ```WINEDLLOVERRIDES="winhttp.dll=n,b" %command%``` for it to load the Doorstop DLL

**Comment by newman55** [comment]
Can you link to the source?

**Comment by ToastedWookiee** [comment]
Personally tested, but based on info from: https://github.com/piotrulos/MSCModLoader/issues/123
The Steam command just bypasses the need to use protontricks winecfg to set the DLL override.

The command sets it to load the native, or local file, before using the default builtin proton file.
